[project]
name = "agentic-slack-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.18",
    "emoji-sentiment>=0.0.5",
    "pydantic-settings>=2.9.1",
    "pydantic-settings-yaml>=0.2.0",
    "rich>=14.0.0",
    "slack-bolt>=1.23.0",
    "structlog>=25.3.0",
]
